### ISSUE TITLE
[Feature Request] Add resume support

### ISSUE THREAD

**Issue by UsamaKarim** [ysfchn/SamFetch#4]
Hi,
You are doing a great job <3
Can you please add resume support for the file

**Comment by ysfchn** [comment]
> You are doing a great job <3

Thanks 😄

> Can you please add resume support for the file

I think I can't add it because SamFetch is just a REST API, not a download client. And it doesn't store what you download and who downloaded the file.

**Comment by UsamaKarim** [comment]
> I think I can't add it because SamFetch is just a REST API, not a download client. And it doesn't store what you download and who downloaded the file.

We might need to do a fix for Heroku 😬
