### ISSUE TITLE
[Feature Request] Add file size support

### ISSUE THREAD

**Issue by UsamaKarim** [ysfchn/SamFetch#5]
Can you please add file size support?

**Comment by ysfchn** [comment]
SamFetch already supports showing the file size. When you call the `/api/binary` endpoint it returns the file size as a number and human-readable format.

![image](https://user-images.githubusercontent.com/54748183/110207437-82398780-7e94-11eb-8588-1019cc7ec4b6.png)

**Comment by UsamaKarim** [comment]
I am sorry! I was talking about size while downloading the file. But I think it could be fixed if we somehow enable file resume support..
![image](https://user-images.githubusercontent.com/64292174/110425235-d7a8ab00-80c5-11eb-86ce-c84aff0524b9.png)

**Comment by ysfchn** [comment]
> I am sorry! I was talking about size while downloading the file.

No problem! But it directly sends the bytes to the one who is downloading the file while decrypting it, so SamFetch doesn't know when will it end without downloading the whole file first. It downloads the file in the same progress as you. But I will open this anyway as maybe it can be implemented.

**Comment by UsamaKarim** [comment]
Yaaaayyy!!! Thanks <3

**Comment by ysfchn** [comment]
You're welcome 😁
